Newsweek-clone
abongsjoel/Newsweek-clone pull request #1
Opened 2020-11-13 14:03 UTC by abongsjoel

In this project, I clone the Newsweek homepage using semantic HTML5 elements, Bootstrap4 as well as plain CSS3. The page starts with a header section that uses the Bootstrap4 navbar classes to make it responsive. The main part of the page contains a set of articles that are aligned differently on different screen sizes using Bootstrap4 Grid system.

2020-11-14 00:31 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @abongsjoel 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] MIT license link is missing in the readme file.
- [ ] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [ ] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/99132503-486c1900-2638-11eb-8f4a-6b3897ab750f.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/) ([screenshot](https://user-images.githubusercontent.com/29689273/94326203-fa358480-ffbb-11ea-81ec-b2704fb93212.png) from Pathwright)
- [ ] Add the description for `alt` attribute (For detail see the inline comments)
- [ ] Social media icon should have the navigation link

### IN THE MAGAZINE
- [ ] Manage the spaces like the original section, as explained in image

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://abongsjoel.github.io/Newsweek-clone/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/99133067-4440fb00-263a-11eb-808d-30cace8335c3.png)|![clone](https://user-images.githubusercontent.com/29689273/99133068-460abe80-263a-11eb-9cf1-8c4a36d0c28f.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-11-14 00:31 UTC, umairarshadbutt commented on css/style.css
> +  padding-top: 4rem !important;
Remove the `important`

2020-11-14 00:31 UTC, umairarshadbutt commented on css/style.css
> +    padding-top: 10.5rem !important;
Remove the `important`

2020-11-14 00:31 UTC, umairarshadbutt commented on css/style.css
> +    font-size: 1.2rem !important;
Remove the `important`

2020-11-14 00:31 UTC, umairarshadbutt commented on css/style.css
> +    padding: 0.5rem 0 !important;
Remove the `important`

2020-11-14 00:31 UTC, umairarshadbutt commented on index.html
> +              <img class="w-100" src="https://d.newsweek.com/en/full/1667965/chess-womens-chess-queens-gambit.png?w=397&h=397&f=35386f73ca5a1a7a87a128f9bd61dd2c" alt="">
Add the description for `alt` attribute

2020-11-14 00:31 UTC, umairarshadbutt commented on index.html
> +              <img class="w-100" src="https://d.newsweek.com/en/full/1669014/canada-emigraton-trump-presidential-election.jpg?w=397&h=397&f=01273440ad3df483a50a5546ffd0a938" alt="">
Add the description for `alt` attribute

2020-11-14 00:31 UTC, umairarshadbutt commented on index.html
> +          <img class="w-100" src="https://d.newsweek.com/en/full/1667965/chess-womens-chess-queens-gambit.png?w=397&h=397&f=35386f73ca5a1a7a87a128f9bd61dd2c" alt="">
Add the description for `alt` attribute

2020-11-14 00:31 UTC, umairarshadbutt commented on index.html
> +              <img class="position-absolute top-image" src="https://d.newsweek.com/en/full/1668137/cover-november-20-2020.jpg?w=170&q=95&f=4908b956c71162b16d2cf0426b9afcbf" alt="">
Add the description for `alt` attribute

2020-11-16 01:30 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @abongsjoel **

Great job with the project so far, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] please make sure to remove the horizontal margin in the main section.

- [ ] please make sure to use another logo png picture because the is one is pixelized. 

- [ ] please make sure to correct the issue mentioned by the previous TSE which is that the in the magazine section pictures are too small. here are some tips:

- set a fixed height and width for the images, and use the object-fit CSS attribute to make them look natural.


please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2020-11-16 07:02 UTC, descholar-ceo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @abongsjoel  , your project is approved :tada: :tada: :tada: 
You have implemented all requested changes for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-11-16 14:28 UTC, merged